# Generated by Django 4.0.3 on 2022-04-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_no', models.CharField(max_length=254)),
                ('trans_type', models.CharField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=100, null=True)),
                ('payment_change', models.DecimalField(blank=True, decimal_places=2, max_digits=9, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('tax', models.CharField(blank=True, max_length=100, null=True)),
                ('disc', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
